import pyndri
from os.path import join
from tools4text import read_word_dict
from tqdm import tqdm
from math import log
import docopt

if __name__ == '__main__':
    args = docopt.docopt("""
        Usage:
            embed_idf.py --i=<indexed_data> --d=<word_dict_file> --o=<output_folder>

        Example:
            embed_idf.py --i=/home/thiziri/Documents/DOCTORAT/COLLECTION/Indri_index/AP88  

        Options:
            --i=<indexed_data>    Gives the INDRI index of the collection.
            --d=<word_dict_file>    Gives the word_dict.txt file generated by MatchZoo. 
            --o=<output_folder>    Gives the output folder where constructed embed.idf file will be stored.

        """)

    print("Reading index ...")
    index = pyndri.Index(args["--i"])
    token2id, id2token, id2df = index.get_dictionary()
    id2tf = index.get_term_frequencies()

    print("Reading word_dict_file ...")
    w_dict = read_word_dict(args["--d"])

    out = open(join(args["--o"], "embed.idf"), "w")

    for w in tqdm(w_dict):
        try:
            # idf = log((index.maximum_document()-1-id2df[token2id[w_dict[w]]]+0.0)/id2df[token2id[w_dict[w]]]+0.0)
            idf = log((index.maximum_document()-1)/id2df[token2id[w_dict[w]]])
        except:
            idf = 0.0
        out.write("{} {}\n".format(w, idf))

    print("Finished.")
